Repository auth0/blog, pull requests merged in 2018-04, with the labels that each got.

#1433 Security Risk: 20+ Billion IoT Devices by 2020
  _posts/2018-04-02-security-risk-20-plus-billion-iot-devices-by-2020.markdown
Labels: Needs Assets 👩‍🎨, Needs SEO Review 🧙‍♂️, Ready to Publish 🚀

#1432 Using Python, Flask, and Angular to Build Modern Web Apps - Part 3
  _posts/2018-03-15-using-python-flask-and-angular-to-build-modern-web-apps-part-2.markdown
  _posts/2018-04-03-using-python-flask-and-angular-to-build-modern-web-apps-part-3.markdown
Labels: Needs Assets 👩‍🎨, Ready to Publish 🚀

#1431 Android best practices
  _posts/2018-04-05-best-practices-in-android-development.markdown
Labels: Needs Assets 👩‍🎨, Ready to Publish 🚀

#1448 Update custom domains post.
  _posts/2018-01-16-introducing-custom-domains-preview-with-auth0.markdown
Labels: Ready to Publish 🚀, Reviewed 👮

#1421 Developing Web Apps with ASP.NET Core 2.0 and React - Part 3
  _posts/2018-04-10-developing-web-apps-with-asp-dot-net-core-2-dot-0-and-react-part-3.markdown
Labels: Needs Assets 👩‍🎨, Ready to Publish 🚀

#1452 Renaming Clients to Applications and Centralized to Universal
  _includes/asides/README.md
  _includes/asides/about-auth0.markdown
  _includes/asides/android.markdown
  _includes/asides/angular.markdown
  _includes/asides/express-gateway.markdown
  _includes/asides/node.markdown
  _includes/asides/react.markdown
  _includes/asides/spring-boot.markdown
  _includes/asides/vue.markdown
  _posts/2014-01-07-angularjs-authentication-with-cookies-vs-token.markdown
  _posts/2015-10-07-refresh-tokens-what-are-they-and-when-to-use-them.markdown
  _posts/2016-04-13-authentication-in-golang.markdown
  _posts/2017-04-18-vuejs2-authentication-tutorial.markdown
  _posts/2017-12-28-symfony-tutorial-building-a-blog-part-1.markdown
  _posts/2018-01-02-run-a-loopback-app-on-google-app-engine.markdown
  _posts/2018-01-10-implementing-single-sign-on-in-b2c-applications.markdown
  _posts/2018-01-11-apigateway-microservices-superglue.markdown
  _posts/2018-01-18-deploying-javascript-apps-part-2.markdown
  _posts/2018-01-23-how-to-authenticate-firebase-and-angular-with-auth0-part-1.markdown
  _posts/2018-02-01-building-real-time-web-applications-using-wolkenkit.markdown
  _posts/2018-02-13-developing-games-with-react-redux-and-svg-part-3.markdown
  _posts/2018-02-15-developing-web-apps-with-asp-dot-net-core-2-dot-0-and-react-part-1.markdown
  _posts/2018-02-20-developing-web-apps-with-asp-dot-net-core-2-dot-0-and-react-part-2.markdown
  _posts/2018-03-01-building-a-blog-with-gatsby-react-and-webtask.markdown
  _posts/2018-03-13-using-python-flask-and-angular-to-build-modern-apps-part-1.markdown
  _posts/2018-03-15-using-python-flask-and-angular-to-build-modern-web-apps-part-2.markdown
  _posts/2018-03-20-build-robust-apps-with-mithril-and-auth0.md
  _posts/2018-03-23-symfony-tutorial-building-a-blog-part-3.markdown
  _posts/2018-04-03-using-python-flask-and-angular-to-build-modern-web-apps-part-3.markdown
  _posts/2018-04-05-best-practices-in-android-development.markdown
  _posts/2018-04-09-4-tools-for-threat-intelligence.markdown
  _posts/2018-04-10-aws-summit-how-agl-increased-ttv-and-customer-experience.markdown
  _posts/2018-04-10-developing-web-apps-with-asp-dot-net-core-2-dot-0-and-react-part-3.markdown
Labels: Do Not Merge - Scheduled 🕐

#1416 JWT BCP draft post
  _posts/2018-04-11-a-look-at-the-latest-draft-for-jwt-bcp.markdown
Labels: Needs SEO Review 🧙‍♂️, Ready to Publish 🚀

#1454 Application and Universal Login update.
  _posts/2016-04-13-authentication-in-golang.markdown
  _posts/2016-09-29-angular-2-authentication.markdown
  _posts/2016-11-21-building-and-authenticating-nodejs-apps.markdown
Labels: Do Not Merge - Scheduled 🕐

#1460 Renaming "clients" -> "applications" & "centralized login" -> "universal login"
  _includes/asides/README.md
  _includes/asides/android.markdown
  _includes/asides/angular.markdown
  _includes/asides/express-gateway.markdown
  _includes/asides/node.markdown
  _includes/asides/react.markdown
  _includes/asides/spring-boot.markdown
  _includes/asides/vue.markdown
  _posts/2014-01-07-angularjs-authentication-with-cookies-vs-token.markdown
  _posts/2015-10-07-refresh-tokens-what-are-they-and-when-to-use-them.markdown
  _posts/2015-11-13-build-an-app-with-vuejs.markdown
  _posts/2016-04-13-authentication-in-golang.markdown
  _posts/2016-06-23-creating-your-first-laravel-app-and-adding-authentication.markdown
  _posts/2016-09-20-securing-spring-boot-with-jwts.markdown
  _posts/2016-09-29-angular-2-authentication.markdown
  _posts/2016-11-21-building-and-authenticating-nodejs-apps.markdown
  _posts/2016-12-05-how-saml-authentication-works.markdown
  _posts/2017-04-18-vuejs2-authentication-tutorial.markdown
  _posts/2017-12-07-securing-asp-dot-net-core-2-applications-with-jwts.markdown
  _posts/2017-12-28-symfony-tutorial-building-a-blog-part-1.markdown
  _posts/2018-01-02-run-a-loopback-app-on-google-app-engine.markdown
  _posts/2018-01-10-implementing-single-sign-on-in-b2c-applications.markdown
  _posts/2018-01-11-apigateway-microservices-superglue.markdown
  _posts/2018-01-18-deploying-javascript-apps-part-2.markdown
  _posts/2018-01-23-how-to-authenticate-firebase-and-angular-with-auth0-part-1.markdown
  _posts/2018-02-01-building-real-time-web-applications-using-wolkenkit.markdown
  _posts/2018-02-13-developing-games-with-react-redux-and-svg-part-3.markdown
  _posts/2018-02-15-developing-web-apps-with-asp-dot-net-core-2-dot-0-and-react-part-1.markdown
  _posts/2018-02-20-developing-web-apps-with-asp-dot-net-core-2-dot-0-and-react-part-2.markdown
  _posts/2018-03-01-building-a-blog-with-gatsby-react-and-webtask.markdown
  _posts/2018-03-15-using-python-flask-and-angular-to-build-modern-web-apps-part-2.markdown
  _posts/2018-03-20-build-robust-apps-with-mithril-and-auth0.md
  _posts/2018-03-23-symfony-tutorial-building-a-blog-part-3.markdown
  _posts/2018-04-05-best-practices-in-android-development.markdown
Labels: Do Not Merge - Scheduled 🕐

#1459 Typos and grammar fixes.
  _posts/2017-02-24-sha-1-collision-attack.markdown
Labels: Needs Review 🤔

#1438 Managed service providers post.
  _posts/2018-04-17-what-are-managed-service-providers.markdown
Labels: Needs Assets 👩‍🎨, Reviewed 👮

#1475 Japan's Digital Transformation Driving Public Cloud Spend
  _posts/2018-04-23-japan-digital-transformation-driving-public-cloud-spend.markdown
Labels: Needs Assets 👩‍🎨, Reviewed 👮

#1476 National Geographic selects Auth0 for Identity Management of Global Properties
  _posts/2018-04-23-national-geographic-selects-auth0-for-identity-management-of-global-properties.markdown
Labels: Needs Assets 👩‍🎨, Reviewed 👮

#1338 New Features for Developing AngularJS Applications - Part 1: Component-Based Architecture
  _posts/2018-04-24-new-features-for-developing-angularjs-applications-part-1.markdown
Labels: Needs Assets 👩‍🎨, Reviewed 👮

#1465 Hashing Passwords: One-Way Road to Security
  _posts/2018-04-25-hashing-passwords-one-way-road-to-security.md
Labels: Needs SEO Review 🧙‍♂️, Reviewed 👮

#1477 Developing AngularJS Applications - Part 2: Component-Based Application
  _posts/2018-04-26-developing-angularjs-apps-part-2.markdown
Labels: Ready to Publish 🚀, Reviewed 👮

#1486 Remove deprecated "user impersonation" feature from post
  _posts/2018-04-27-strong-identity-management-system-eases-transition-to-hybrid-cloud.md
Labels: Reviewed 👮

#1482 RxJS 6: What's new and what has changed?
  _posts/2018-04-30-whats-new-in-rxjs-6.md
Labels: Reviewed 👮
