Repository auth0/blog, pull requests merged in 2018-06, with the labels that each got.

#1494 3 Tools to Improve Your Customer Intelligence
  _posts/2018-06-01-three-tools-to-improve-your-customer-intelligence.markdown
Labels: [PR] Ready to merge 🎉

#1535 Brace Yourself: The GDPR Ripple Effect in California
  _posts/2018-06-04-brace-yourself-the-gdpr-ripple-effect-in-california.markdown
Labels: Needs Assets 👩‍🎨, Ready to Publish 🚀

#1527 Cypress: Write Automated Tests to Validate Web Applications
  _posts/2018-06-05-cypress-write-automated-tests-to-validate-web-applications.markdown
Labels: Guest Author, Needs Assets 👩‍🎨, Ready to Publish 🚀

#1531 Introduction to Web Authentication: The New W3C Spec
  _posts/2018-06-06-introduction-to-web-authentication.markdown
Labels: Needs Assets 👩‍🎨, Ready to Publish 🚀

#1552 Nonprofit MiVoz Hopes to Upgrade Democracy with Auth0
  _posts/2018-06-08-nonprofit-mivoz-hopes-to-upgrade-democracy-with-auth0.markdown
Labels: Needs Assets 👩‍🎨

#1562 How Social Login Can Pave the Way for a Digital Shift in Grocery
  _posts/2018-06-11-how-social-login-can-pave-the-way-for-a-digital-shift-in-grocery.markdown
Labels: Ready to Publish 🚀

#1554 Webinar: The Need for Universal Identity Management with 415 Research
  _posts/2018-06-11-webinar-the-need-for-universal-identity-management-451-research.markdown
Labels: Needs Assets 👩‍🎨

#1564 Removed posts with wrong information.
  _posts/2014-01-07-angularjs-authentication-with-cookies-vs-token.markdown
  _posts/2014-01-15-auth-with-socket-io.markdown
  _posts/2016-05-31-cookies-vs-tokens-definitive-guide.markdown
  _posts/2016-05-31-jp-cookies-vs-tokens-definitive-guide.markdown
Labels: bug 🔥

#1468 Vue.js and AWS Lambda: Developing Production-Ready Apps (Part 1)
  _posts/2018-06-13-vue-js-and-lambda-developing-production-ready-apps-part-1.markdown
Labels: Needs Assets 👩‍🎨, Ready to Publish 🚀

#1533 How Two-Factor Authentication (2FA) Can Help Financial Institutions Reduce Data Breaches
  _posts/2018-06-18-how-two-factor-authentication-can-help-financial-institutions-reduce-data-breaches.markdown
Labels: Needs Assets 👩‍🎨, Ready to Publish 🚀

#1501 Creating Web Components with Stencil
  _posts/2018-06-19-creating-web-components-with-stencil.markdown
Labels: Guest Author, Needs Assets 👩‍🎨, Ready to Publish 🚀

#1541 HelloWorld: With Auth0
  _posts/2018-06-20-helloworld-with-auth0.markdown
Labels: Needs Assets 👩‍🎨, Ready to Publish 🚀

#1522 Getting Started with the New WebVR API
  _posts/2018-06-21-getting-started-with-the-new-webvr-api.markdown
Labels: Guest Author, Needs Assets 👩‍🎨, Ready to Publish 🚀

#1575 Open standards won’t save you from vendor lock-in
  _posts/2018-06-21-open-standards-wont-save-you-from-vendor-lock-in.md
Labels: Needs Review 🤔

#1579 Gartner MQ Press Release
  _posts/2018-06-25-auth0-debuts-as-a-visionary-in-gartner-mq-for-access-management.markdown
Labels: Ready to Publish 🚀

#1523 sarah jorgenson emberjs auth
  _posts/2018-06-26-build-and-authenticate-an-emberjs-3-application.markdown
Labels: Guest Author, Ready to Publish 🚀

#1544 Why Laravel is the recommended framework for secure, mission-critical applications?
  _posts/2018-06-28-why-laravel-is-the-recommended-framework-for-secure-mission-critical-applications.md
Labels: Guest Author, Ready to Publish 🚀

#1543 Create Your Quick GDPR Compliance Checklist blog post
  _posts/2018-06-29-your-quick-gdpr-compliance-checklist.markdown
Labels: Needs Assets 👩‍🎨
