Repository auth0/blog, pull requests merged in 2018-05, with the labels that each got.

#1488 Staffing intro post
  _posts/2018-05-01-auth0-welcomes-vittorio-bertocci.markdown
Labels: Ready to Publish 🚀

#1479 What's new in Angular 6?
  _posts/2018-05-02-whats-new-in-angular6.markdown
Labels: Ready to Publish 🚀, Reviewed 👮, [PR] Ready to merge 🎉

#1489 NodeJS 10: The New, The Changed, and the Deprecated
  _posts/2018-05-02-nodejs-10-new-changes-deprecations.md
Labels: Needs Review 🤔

#1472 Adding Salt to Hashing: A Better Way to Store Passwords
  _posts/2018-05-03-adding-salt-to-hashing-a-better-way-to-store-passwords.md
Labels: Reviewed 👮

#1498 Five things to be a better leader draft, by Jenny.
  _posts/2018-05-04-five-things-to-be-a-better-leader.markdown
Labels: Needs Assets 👩‍🎨, Reviewed 👮

#1491 Re-adding Prospers article to publish later
  _posts/2018-05-07-whats-new-in-angular6.markdown
Labels: Ready to Publish 🚀, Reviewed 👮

#1508 Google I/O Day 1
  _posts/2018-05-09-googleio-summary-day-one.markdown
Labels: Ready to Publish 🚀, Reviewed 👮

#1514 Google I/O Day 2
  _posts/2018-05-10-googleio-summary-day-two.markdown
Labels: Ready to Publish 🚀, Reviewed 👮

#1516 Google I/O Day 3
  _posts/2018-05-11-googleio-summary-day-three.markdown
Labels: Ready to Publish 🚀, Reviewed 👮

#1518 Information Warfare Offensive
  _posts/2018-05-14-information-warfare-offensive.markdown
Labels: Needs Assets 👩‍🎨

#1511 Add new blogpost for shiny authorization and fix old install steps
  _posts/2016-12-13-adding-authentication-to-shiny-server.markdown
  _posts/2018-05-16-authentication-and-authorization-with-shiny-server-pro-and-auth0.markdown
Labels: Ready to Publish 🚀, Reviewed 👮

#1493 Ruby on Rails—Killer Workflow with Docker (Part 1)
  _posts/2018-05-17-ruby-on-rails-killer-workflow-with-docker-part-1.md
Labels: Guest Author, Needs Assets 👩‍🎨, Ready to Publish 🚀

#1443 Create Digital Success through Customer Identity and Access Management post
  _posts/2018-05-21-digital-success-through-customer-identity-and-access-management.md
Labels: Needs Assets 👩‍🎨

#1499 Ruby on Rails—Killer Workflow with Docker (Part 2)
  _posts/2018-05-24-ruby-on-rails-killer-workflow-with-docker-part-2.md
Labels: Guest Author, Ready to Publish 🚀

#1515 Hashing in Action: Understanding bcrypt
  _posts/2018-05-31-hashing-in-action-understanding-bcrypt.md
Labels: Ready to Publish 🚀, Reviewed 👮
