Repository auth0/blog, pull requests merged in 2018-07, with the labels that each got.

#1455 Breaking down master data management
  _posts/2018-07-02-breaking-down-master-data-management.markdown
Labels: Needs Assets 👩‍🎨

#1583 Vue.js and AWS Lambda: Developing Production-Ready Apps (Part 2)
  _posts/2018-06-13-vue-js-and-lambda-developing-production-ready-apps-part-1.markdown
  _posts/2018-07-03-vue-js-and-lambda-developing-production-ready-apps-part-2.markdown
Labels: Ready to Publish 🚀

#1588 Suggested fixes: Why Laravel is the Recommended Framework for Secure, Mission-Critical Applications
  _posts/2018-06-28-why-laravel-is-the-recommended-framework-for-secure-mission-critical-applications.md
Labels: Needs Review 🤔

#1576 Keep API Backward Compatibility with Express Gateway
  _posts/2018-01-11-apigateway-microservices-superglue.markdown
  _posts/2018-03-26-application-metrics-with-express-gateway.markdown
  _posts/2018-07-05-keep-api-backward-compatibility-with-express-gateway.markdown
Labels: Guest Author, Ready to Publish 🚀

#1538 Upgrade Your AngularJS Authentication Service
  _posts/2018-07-10-upgrade-your-angularjs-authentication-service.markdown
Labels: Guest Author, Ready to Publish 🚀

#1563 Machine-to-machine auth post draft.
  _posts/2018-07-11-using-m2m-authorization.markdown
Labels: Needs Assets 👩‍🎨, Reviewed 👮

#1577 Building Audio Players with Angular, Ionic, RxJS, and NgRx
  _posts/2018-07-12-building-an-audio-player-app-with-ionic-angular-rxjs-and-ngrx.markdown
Labels: Guest Author, Ready to Publish 🚀

#1605 Auth0 Expands Reach of Global Partner Program (PR)
  _posts/2018-07-16-auth0-expands-reach-of-global-partner-program.markdown
Labels: Ready to Publish 🚀

#1534 How the Right IAM Tools Will Help Insurance Teams Make the Shift to Digital
  _posts/2018-07-16-how-identity-and-access-management-tools-help-insurance-teams.markdown
Labels: Needs Assets 👩‍🎨, Ready to Publish 🚀

#1606 Building a Movie Listing Application with Aurelia and TypeScript
  _posts/2018-07-17-building-a-movie-listing-application-with-aurelia-and-typescript.markdown
Labels: Guest Author, Ready to Publish 🚀

#1608 Developing Mobile Apps with Xamarin Forms and Azure Functions
  _posts/2018-07-18-developing-mobile-apps-with-xamarin-forms-and-azure-functions.markdown
Labels: Guest Author, Needs Assets 👩‍🎨, Ready to Publish 🚀

#1581 Create 2018-06-26-how-auth0-makes-your-apps-more-secure.md
  _posts/2018-07-19-how-auth0-makes-your-apps-more-secure.md
Labels: Needs Review 🤔, Needs SEO Review 🧙‍♂️

#1601 Submitting A Look at the Android ML Kit SDK article
  _posts/2018-07-10-a-look-at-the-android-ml-kit-sdk.markdown
Labels: Guest Author, [PR] WIP 👩‍💻

#1582 3 Tools For Digital Transformation in the Airline Industry
  _posts/2018-07-23-3-tools-for-digital-transformation-in-airline-industry.md
Labels: Needs Review 🤔

#1614 A Look at the Android ML Kit SDK
  _posts/2018-07-24-a-look-at-android-ml-kit-the-machine-learning-sdk.markdown
Labels: Guest Author, Ready to Publish 🚀

#1622 Developing Real-Time Web Applications with Server-Sent Events
  _posts/2018-07-25-developing-real-time-web-applications-with-server-sent-events.markdown
Labels: Guest Author, Ready to Publish 🚀

#1609 Cloud scale
  _posts/2018-07-26-cloud-scale-thinking-from-day-one-for-your-saas-products.markdown
Labels: Guest Author, Ready to Publish 🚀

#1574 Full-Stack TypeScript Apps - Part 1: Developing Backend APIs with Nest.js
  _posts/2018-07-25-full-stack-typescript-apps-part-1-developing-backend-apis-with-nestjs.markdown
Labels: Guest Author, Ready to Publish 🚀
