Repository auth0/blog, pull requests merged in 2018-02, with the labels that each got.

#1354 Add Are you ready for GDPR article
  _posts/2018-02-09-are-you-gdpr-ready.markdown
Labels: Ready to Publish

#1355 GCP press release
  _posts/2018-02-12-auth0-joins-the-google-cloud-partner-platform.markdown
Labels: Ready to Publish

#1358 Developing Games with React, Redux, and SVG - Part 3
  _posts/2018-02-08-developing-games-with-react-redux-and-svg-part-2.markdown
  _posts/2018-02-13-developing-games-with-react-redux-and-svg-part-3.markdown
Labels: Ready to Publish

#1308 What is Data Security?
  _posts/2018-02-14-what-is-data-security.markdown
Labels: Needs Assets, Reviewed

#1333 Developing Web Apps with ASP.NET Core 2.0 and React - Part 1
  _posts/2018-02-15-developing-web-apps-with-asp-dot-net-core-2-dot-0-and-react-part-1.markdown
Labels: Needs Assets, Ready to Publish

#1328 The 6 Billion Reason Your Business Needs Advanced Fraud Protection
  _posts/2018-02-16-the-6-billion-reason-your-business-needs-advanced-fraud-protection.markdown
Labels: Ready to Publish

#1360 Developing Web Apps with ASP.NET Core 2.0 and React - Part 2
  _posts/2018-02-20-developing-web-apps-with-asp-dot-net-core-2-dot-0-and-react-part-2.markdown
Labels: Needs Assets, Ready to Publish

#1375 Laravel 5.6: What's New?
  _posts/2018-02-21-laravel-5-6-release-what-is-new.markdown
Labels: Ready to Publish, Reviewed

#1367 SparkPost integration blog post
  _posts/2018-02-22-using-sparkpost-as-a-email-provider-with-auth0.markdown
Labels: Needs SEO Review 🧙‍♂️, Reviewed 👮

#1384 Webpack 4.0 Release: What's New?
  _posts/2018-02-26-webpack-4-release-what-is-new.markdown
Labels: Ready to Publish 🚀

#1361 Feature/updating symfony series to symfony 4
  _posts/2017-12-28-symfony-tutorial-building-a-blog-part-1.markdown
  _posts/2018-01-04-creating-symfony-blog-part-2.markdown
Labels: [PR] Ready to merge 🎉

#1386 8 Ways to Avoid Healthcare Breaches
  _posts/2018-02-27-8-ways-to-avoid-healthcare-breaches.markdown
Labels: Needs Assets 👩‍🎨, Reviewed 👮

#1390 Auth0 not affected by SAML issues blog post
  _posts/2018-02-28-auth0-not-affected-by-saml-vulnerabilities-identified-by-duo-security.markdown
Labels: Ready to Publish 🚀, Reviewed 👮
