Repository auth0/blog, pull requests merged in 2018-08, with the labels that each got.

#1616 Four Cybersecurity Attacks Your Employees Need to Know
  _posts/2018-07-30-four-cybersecurity-attacks-you-need-to-know.markdown
Labels: Ready to Publish 🚀

#1618 What Data Did Facebook Really Give Cambridge Analytica?
  _posts/2018-08-03-what-data-did-facebook-really-give-cambridge-analytica.markdown
Labels: Ready to Publish 🚀

#1628 SEO low hanging fruit - miscellaneous optimizations throughout
  _posts/2016-10-17-bad-login-experiences.markdown
  _posts/2017-12-20-developing-npm-packages.markdown
  _posts/2018-05-22-building-modern-applications-with-django-and-vuejs.markdown
Labels: [PR] Ready to merge 🎉

#1640 Adding references to new M2M landing page
  _posts/2018-07-10-upgrade-your-angularjs-authentication-service.markdown
  _posts/2018-07-11-using-m2m-authorization.markdown
Labels: Ready to Publish 🚀

#1612 Create Secure Angular Apps in the Cloud with StackBlitz and Auth0
  _posts/2018-07-27-how-to-create-angular-apps-with-auth0-and-stackblitz.markdown
Labels: Ready to Publish 🚀

#1642 Philz Coffee Authenticates Mobile App Users with Auth0
  _posts/2018-08-07-philz-coffee-authenticates-mobile-app-users-with-auth0.markdown
Labels: Ready to Publish 🚀

#1607 Introduction to Redis: Installation, CLI Commands, and Data Types
  _posts/2018-08-08-introduction-to-redis-install-cli-commands-and-data-types.markdown
Labels: Ready to Publish 🚀, Reviewed 👮

#1637 SEO lang attribute - optimizations throughout
  _includes/locales.html
  _layouts/amp.html
  _layouts/default.html
  _posts/2015-10-07-jp-refresh-tokens-what-are-they-and-when-to-use-them.markdown
  _posts/2016-09-29-jp-angular-2-authentication.markdown
  _posts/2016-10-17-jp-sso-login-key-benefits-and-implementation.markdown
  _posts/2016-11-21-jp-building-and-authenticating-nodejs-apps.markdown
  _posts/2016-12-05-jp-how-saml-authentication-works.markdown
  _posts/2017-02-21-jp-reactjs-authentication-tutorial.markdown
  _posts/2017-04-18-jp-vuejs2-authentication-tutorial.markdown
  _posts/2017-12-07-jp-securing-asp-dot-net-core-2-applications-with-jwts.markdown
Labels: [PR] Ready to merge 🎉

#1649 SEO AMP fixes for indexing
  _layouts/amp_index.html
Labels: [PR] Ready to merge 🎉

#1626 Continuous Deployment Pipelines and Open-Source Web Apps
  _posts/2018-08-09-continuous-deployment-pipelines-and-open-source-node-js-web-apps.markdown
Labels: Guest Author, Needs Assets 👩‍🎨

#1620 Secure Your Gaming Company
  _posts/2018-08-10-secure-your-gaming-company-with-auth0-fraud-protection.markdown
Labels: Ready to Publish 🚀

#1633 React Context API: Managing State with Ease
  _posts/2018-08-14-react-context-api-managing-state-with-ease.markdown
Labels: Guest Author

#1643 Auth0 Architecture: Running In Multiple Cloud Providers And Regions
  _posts/2018-08-15-auth0-architecture-running-in-multiple-cloud-providers-and-regions.markdown
Labels: Ready to Publish 🚀

#1632 Supporting Government-Issued IDs as Social Connections with Auth0
  _posts/2018-08-16-configuring-swissid-login-into-custom-applications.markdown
Labels: Needs Assets 👩‍🎨

#1623 Use Auth0 Tools To Securely Manage Your User Database
  _posts/2018-08-17-use-auth0-tools-to-securely-manage-your-user-database.markdown
Labels: Needs Assets 👩‍🎨, Ready to Publish 🚀

#1653 TypeScript 3: Tuple Ware and Into the Unknown
  _posts/2018-08-21-typescript-3-tuple-ware-and-intro-the-unknown.markdown
Labels: Reviewed 👮

#1590 SEO - Adding metadescription field and reworking post includes - WIP
  Rakefile
  _includes/amp/banner_post.html
  _includes/banner_post.html
  _includes/head.html
  _includes/sharing_metas.html
  _includes/social_buttons.html
  post-cheat-sheet.markdown
Labels: [PR] Ready to merge 🎉

#1654 Golang & Angular Series - Part 1: Developing and Securing Golang APIs
  _posts/2018-08-22-developing-golang-and-angular-apps-part-1-backend-api.markdown
Labels: Guest Author, Needs Assets 👩‍🎨

#1667 Golang & Angular Series - Part 2: Developing and Securing Angular Apps
  _posts/2018-08-23-developing-golang-and-angular-apps-part-2-angular-front-end.markdown
Labels: Guest Author, Needs Assets 👩‍🎨

#1693 Styling nav CTA - orange button styled like others
  _includes/amp/amp_sidebar.html
  _sass/amp/sidebar.scss
Labels: [PR] Ready to merge 🎉

#1664 Migrate cakephp post from auth0.js
  _posts/2017-06-01-creating-your-first-cakephp-app.markdown
Labels: Reviewed 👮

#1701 Update link for category in front matter generated.
  Rakefile
Labels: Needs Review 🤔

#1698 Adding Schema markup for Author/Person - jobTitle
  _includes/profile_card.html
Labels: [PR] Ready to merge 🎉

#1697 Schema markup optimizations
  _includes/amp/banner_post.html
  _includes/banner_post.html
  _layouts/post.html
Labels: [PR] Ready to merge 🎉

#1696 React Tutorial: Building and Securing Your First App
  _posts/2017-02-21-reactjs-authentication-tutorial.markdown
  _posts/2018-08-28-react-tutorial-building-and-securing-your-first-app.markdown
Labels: Ready to Publish 🚀

#1702 Add post_length to Rakefile and post length bash script
  Rakefile
  post-cheat-sheet.markdown
  postlength.sh
Labels: Reviewed 👮, [PR] Ready to merge 🎉

#1687 How Auth0 is Building and Scaling Company Culture
  _posts/2018-08-29-how-auth0-is-building-and-scaling-company-culture.markdown
Labels: [PR] WIP 👩‍💻

#1683 Speedy Introduction to Web Workers
  _posts/2018-08-30-speedy-introduction-to-web-workers.markdown
Labels: Reviewed 👮

#1723 Updated migrate Gigya users to Auth0 article
  _posts/2017-10-03-migrate-your-gigya-users-to-auth0.markdown
Labels: Ready to Publish 🚀
